name: Docker CI

on:
  workflow_call:
  push:
  pull_request:
    types: [opened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd source && docker build . --file Dockerfile --tag ndsp-test:$(date +%s)

    - name: Run Unit Tests and extract results
      run: cd source && docker build . --target export-test-results --file Dockerfile --output type=local,dest=test-results

    - name: List files
      run: ls -la
      
    - name: Publish Test results
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Test Results
        path: '**/*.trx'
        reporter: dotnet-trx

        