name: Docker CI

on:
  workflow_call:
  push:
  pull_request:
    types: [opened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd source && docker build . --file Dockerfile --tag ndsp-test:$(date +%s)